### PR TITLE
Add test dir. Use pytest. Add test config

### PR DESCRIPTION
**Pull request by alisnichenko**
### What
Modified some of the testing practices using pytest.
* Added pytest to the `requirements.txt`
* Modified existing tests and wrote them to an acceptable pytest format.
* Created `init` procedure for testing.
* Removed old testing file

### Why
Testing was confusing and wasn't clear how to run. Now, you can go into the testing directory and simply run `pytest` after downloading the `requirements.txt` file. More documentation will come after that.

Let me know if any of the changes are unnecessary or confusing.

### CODE REVIEW

**Review by Peacewalker365 — COMMENTED** [review]
I totally understand why you said you feel a bit confusing about the pytest.

But the test cases are nicely done. Great job!
(I haven't run the test yet, but I'll do that once I get the chance.)

**Comment by alisnichenko** [comment]
Hey, I modified this PR. Let me know what you think about it.

**Comment by Peacewalker365** [comment]
____________________________________________________ ERROR collecting test session ____________________________________________________
**E:\Projects\CEN4020F21TeamWyoming\test\test_utils.py:6: in <module> 
os.chdir('../src')
E   FileNotFoundError: [WinError 2] The system cannot find the file specified: '../src'**


I got this error message when trying to run the test. I'm doing it on Windows so I guess it's because windows use \ instead of / in paths. Do you know how we can detect the platform in python?

**Comment by alisnichenko** [comment]
Jeez, now we have to deal with platform compatibility. I am not sure if it's necessarily platform error, but here is how you do it:
```python
from sys import platform as _platform

if _platform.startswith('linux'):
    # Linux code.
elif _platform == 'darwin':
    # Mac code.
elif _platform.startswith('win'):
    # Windows code.
else:
    # What the hell are you even running.
```

**Review by alogorzusf — APPROVED** [review]

**Review by Peacewalker365 — APPROVED** [review]

**Pull request merged**
